//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webprojetasarım.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisAnaliz
    {
        public int SatisID { get; set; }
        public int SiparisID { get; set; }
        public int Adet { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public int FirmaID { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
    }
}
