//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webprojetasarım.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.SatisAnaliz = new HashSet<SatisAnaliz>();
        }
    
        public int SiparisID { get; set; }
        public int FirmaID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> SiparisNumarasi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public decimal Tutar { get; set; }
        public int OdemeID { get; set; }
        public bool Silindi { get; set; }
        public int KullaniciID { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public decimal Fiyat { get; set; }
        public string UrunAd { get; set; }
        public Nullable<int> Miktar { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisAnaliz> SatisAnaliz { get; set; }
        public virtual Urunler Urunler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Odeme Odeme { get; set; }
    }
}
