//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webprojetasarım.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Siparisler = new HashSet<Siparisler>();
        }
    
        public int UrunID { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAd { get; set; }
        public int KategoriID { get; set; }
        public int AltKategoriID { get; set; }
        public int FirmaID { get; set; }
        public int Miktar { get; set; }
        public decimal Fiyat { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> YorumID { get; set; }
        public string ResimYolu1 { get; set; }
        public string ResimYolu2 { get; set; }
        public string ResimYolu3 { get; set; }
        public bool Silindi { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
    }
}
